spring:
  datasource:
    url: jdbc:mysql://47.100.24.126:3306/forum?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: jjc9767690804-JJJ
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 47.100.24.126
    port: 6379
    password: jjc9767690804
    timeout: PT10M
  session:
    store-type: redis
    timeout: PT10M

